FROM nginx:latest
RUN rm -rf /etc/nginx/nginx.conf && \
    printf 'events {}\nhttp {\n    server {\n        listen 80;\n        location / {\n            proxy_pass http://note:8000;\n            proxy_set_header Host $host;\n            proxy_set_header X-Real-IP $remote_addr;\n        }\n    }\n}' > /etc/nginx/nginx.conf